### ISSUE TITLE
Subprocess example does not compile with ghc 9.4.8

### ISSUE THREAD

**Issue by cdfa** [sayo-hs/heftia#23]
Hi, thanks for writing this library! I am trying it out in a project for work, but I get a compile error:
```
heftia-effects> Preprocessing executable 'Subprocess' for heftia-effects-0.5.0.0..
heftia-effects> Building executable 'Subprocess' for heftia-effects-0.5.0.0..
heftia-effects> [1 of 1] Compiling Main
heftia-effects> 
heftia-effects> /tmp/stack-e77ef61973196269/heftia-effects-0.5.0.0/Example/Subprocess/Main.hs:19:39: error:
heftia-effects>     • Record update for insufficiently polymorphic field:
heftia-effects>         stdout :: StdStream o
heftia-effects>     • In the third argument of ‘scope’, namely
heftia-effects>         ‘(shell "echo a b c") {stdout = CreatePipe}’
heftia-effects>       In a stmt of a 'do' block:
heftia-effects>         r <- scope
heftia-effects>                @"echo" @SubprocResult (shell "echo a b c") {stdout = CreatePipe}
heftia-effects>                \ _ -> do readStdout'' @"echo"
heftia-effects>       In the second argument of ‘($)’, namely
heftia-effects>         ‘do r <- scope
heftia-effects>                    @"echo" @SubprocResult (shell "echo a b c") {stdout = CreatePipe}
heftia-effects>                    \ _ -> do ...
heftia-effects>             print r & liftIO’
heftia-effects>    |
heftia-effects> 19 |     r <- scope @"echo" @SubprocResult (shell "echo a b c") {stdout = CreatePipe} \_ -> do
heftia-effects>    |    
```

I think this might be due to [this GHC bug](https://gitlab.haskell.org/ghc/ghc/-/issues/16501).
It's strange though, because GHC 9.4.1 is in `tested-with`. I created a reproduction repo [here](https://github.com/cdfa/heftia-repro).
Is there anything heftia can do to work around this?

**Comment by ymdryo** [comment]
Thank you for the report!
I've encountered this error as well. Because of that, in my test suite I've disabled testing for the executable specifically under GHC 9.4.1. Apologies—ideally I shouldn’t have listed 9.4.1 in `tested-with`. The problem doesn’t occur with GHC 9.6.6 or later, so please try upgrading your GHC version. I'm planning to drop support for GHC 9.4.1 in the next release of heftia.

If the issue persists, please feel free to reopen or create a new issue.

**Comment by cdfa** [comment]
Aahh that explains. Thanks!
Do you have a timeline for the next heftia release?

**Comment by ymdryo** [comment]
I haven't had much time for personal development lately, so I'm not sure exactly when it'll be ready. Please expect a timeline of a few months to about half a year.

**Comment by ymdryo** [comment]
I've gone ahead and released a new version v0.6 for now. The documentation is still incomplete, but the implementation itself should be solid.

**Comment by cdfa** [comment]
Wow thanks for the quick update! Sadly we can't upgrade to a new GHC version that quickly haha.
But it's great to see the new unified interface!

**Comment by cdfa** [comment]
Piggybacking a small note on this issue: [the link to the `Provider` example](https://github.com/sayo-hs/heftia/blob/17db8a6b45557bd87782c78849b451ce9446d6f2/README.md?plain=1#L69) in the readme still needs to be updated.

**Comment by ymdryo** [comment]
Ah, you're right. I'll go ahead and fix it.

**Comment by ymdryo** [comment]
@cdfa 
For your information, the library itself should probably still work with GHC 9.4.8. It's just that the Subprocess example results in a compile error.

**Comment by cdfa** [comment]
Yes, I got it work by adding heftia as a submodule and disabling the example in a copy of the cabal file. So far, heftia works well!
